#!/bin/bash
#
# Author: Martin Matusiak <numerodix@gmail.com>
# Licensed under the GNU Public License, version 3.


# load constants and functions
p=$(dirname $(readlink -f $0)); . $p/lib.sh

usage="Usage:  ${b}${tool_name} ${bb}<file(s)>${r} [${b}options${r}]\n
     --start    start after this many seconds (usually for testing)
  -e --end      end after this many seconds (usually for testing)\n
  -C            do sanity check (check for missing tools)
  -z --adv      <show advanced options>
     --version  show ${suite_name} version"

adv_usage="Advanced usage:  ${b}${tool_name} ${bb}<file(s)>${r} [${b}options${r}]
  -o --size     output file size in mb (integer value)
  -1            force 1-pass encoding
  -2            force 2-pass encoding
  -c --crop     autocrop video
  -r --scale    scale video to x:y (integer value or ${bb}0${r}) or ${bb}off${r} to disable
  -f --smooth   use picture smoothing filter
  -D --dryrun   dry run (display encoding parameters without encoding)\n
     --cont     set container format
     --acodec   set audio codec
     --vcodec   set video codec"

shorts="e:o:r:12cfDCz"
longs="start:,end:,adv,version,size:,crop,scale:,smooth,dryrun,cont:,acodec:,vcodec:"
eval $(get_parsecmd "$tool_name" "$shorts" "$longs")

while true; do
    case "$1" in
           --start   ) opts_start=$2; shift 2;;
        -e|--end     ) opts_end=$2; shift 2;;
           --version ) print_version;;

        -o|--size    ) target_size="$2"; shift 2;;
        -1           ) target_passes="1"; shift;;
        -2           ) target_twopass=y;target_passes="2"; shift;;
        -c|--crop    ) autocrop=y; shift;;
        -r|--scale   ) custom_scale="$2"; shift 2;;
        -f|--smooth  ) prescale="spp,";postscale=",hqdn3d"; shift;;
        -D|--dryrun  ) dry_run="y"; shift;;

           --cont    ) opts_cont="$2"; shift 2;;
           --acodec  ) opts_acodec="$2"; shift 2;;
           --vcodec  ) opts_vcodec="$2"; shift 2;;

        -C           ) init_cmds "y"; exit;;
        -z|--adv     ) echo -e "$adv_usage"; exit;;
        --           ) shift ; break ;;
    esac
done

display_tool_banner


if [[ "$opts_start" ]]; then
    startpos="-ss $opts_start"
else
    opts_start=0
fi

if [[ "$opts_end" ]]; then
    endpos="-endpos $opts_end"
fi

if [[ ! "$custom_scale" ]]; then
	custom_scale="off"
fi


if [[ ! "$@" ]]; then
	echo -e "${e}No files to encode, exiting${r}"
    echo -e "$usage"
    exit 2
fi


$mkdir -p logs
if [[ $? != 0 ]] ; then
    echo -e "${e}Could not write to ${bb}$PWD${e}, exiting${r}"
    exit 1
fi


# Set container and codecs

[[ "$opts_cont" ]] && container="$opts_cont"
info=($(container_opts "$container" "$opts_acodec" "$opts_vcodec"))
audio_codec=${info[0]}
video_codec=${info[1]}
ext=${info[2]}
cont=${info[@]:3}

echo -en " - Output format :: "
echo -en "container: ${it}$container${r}"
echo -en "  audio: ${it}$audio_codec${r}"
echo -e  "  video: ${it}$video_codec${r}"



# Display dry-run status

if [[ "$dry_run" ]]; then
	echo -e " * Performing dry-run"
    display_title_line "header"
fi

for mencoder_source in "$@"; do

    if [[ ! -e "$mencoder_source" ]]; then
        echo -e "${e}File ${bb}$mencoder_source${e} does not exist"
        exit 1
    fi

	mencoder_source_quot="\"$(escape_chars "$mencoder_source")\""
	title=${mencoder_source%.*}


    # Display encode status

    if [[ ! "$dry_run" ]]; then
		title_s=$(fill "$(basename "$mencoder_source")" 36 "y")
		echo -en " * Now encoding file ${bb}$title_s${r}"
        if [[ "$opts_end" ]]; then
            end=$(( $opts_start + $opts_end ))
            echo -e "  ${r}[${bb}${opts_start}${r}s - ${bb}${end}${r}s]"
        else
            echo
        fi
    fi


    # Extract information from the title

    info=($(examine_title "$mencoder_source"))
    width=${info[0]}
    height=${info[1]}
    fps=${info[2]}
    length=${info[3]}
    src_abitrate=${info[4]}

    # Do we need to crop?

    if [[ "$autocrop" ]]; then
        echo -en " + Finding out how much to crop...\r"
        info=($(crop_title "$mencoder_source"))
        width=${info[0]}
        height=${info[1]}
        crop_filter="crop=${info[2]},"
        if [[ ! "$width" || ! "$height" || ! "$crop_filter" ]]; then
            echo -e "${e}Crop detection failed${r}              "
            exit 1
        fi
    fi

    # Find out how to scale the dimensions

    scale_info=($(title_scale "$width" "$height" "$custom_scale"))
    width=${scale_info[0]}
    height=${scale_info[1]}
    scale="scale=$width:$height"

    # Estimate filesize of audio

    audio_bitrate=$(acodec_opts "$container" "$audio_codec" "$src_abitrate" "y")
    acodec=$(acodec_opts "$container" "$audio_codec" "$src_abitrate" "")
    audio_size=$(compute_media_size "$length" "$audio_bitrate")

    # Decide bpp

    if [[ "$target_size" ]]; then
        video_size=$(( $target_size - $audio_size ))
        [[ "0" > "$video_size" ]] && video_size=1
        bpp=$(compute_bpp "$width" "$height" "$fps" "$length" "$video_size")
    else
        bpp=$(set_bpp "$video_codec" "$target_twopass")
    fi

    # Reset the number of passes based on the bpp

    unset twopass
    if [[ "$target_passes" ]]; then
        passes="$target_passes"
    else
        passes=$(set_passes "$video_codec" "$bpp")
    fi
    [[ "$passes" = "2" ]] && twopass=y

    # Compute bitrate

    video_bitrate=$(compute_bitrate "$width" "$height" "$fps" "$bpp")

    # Estimate output size
    unset output_size
    if [[ "$target_size" ]]; then
        output_size="$target_size"
    else
        video_size=$(compute_media_size "$length" "$video_bitrate")
        output_size=$(( $video_size+$audio_size ))
    fi



    if [[ "$dry_run" ]]; then

        # Dry run

        filesize="$output_size"
        display_title "$width" "$height" "$fps" "$length" "$bpp" "$passes" "$video_bitrate" "$video_codec" "$audio_bitrate" "$audio_codec" "$filesize" "$mencoder_source"

    else

        # Encode video

        pass=0
        for p in $($seq $passes); do
            pass=$(( $pass + 1 ))

            vcodec=$(vcodec_opts "$video_codec" "$twopass" "$pass" "$video_bitrate")

            cmd="time \
            $nice -n20 \
            $mencoder -v \
            $mencoder_source_quot \
            ${audio} \
            ${subs} \
            ${startpos} \
            ${endpos} \
            -vf ${crop_filter}${prescale}${scale}${postscale} \
            -ovc ${vcodec} \
            -oac ${acodec} \
            -of ${cont}"
            run_encode "$cmd" "$title" "$ext" "$length" "$twopass" "$pass"
        done

        [[ -f "${title}.${ext}.partial" ]] && \
			$mv "${title}.${ext}.partial" "${title}.${ext}"
        $rm divx2pass* 2> /dev/null

        remux_container "$title" "$ext" "$fps" "$container" "$audio_codec" "$video_codec"

    fi

done
