#!/bin/bash
#
# Author: Martin Matusiak <numerodix@gmail.com>
# Licensed under the GNU Public License, version 3.


# load constants and functions
p=$(dirname $(readlink -f $0)); . $p/lib.sh

usage="Usage:  ${b}${tool_name} ${r}[${b}--dev ${bb}/dev/dvd${r} | ${b}--dir ${bb}/path${r} | ${b}--iso ${bb}disc.iso${r}]
  -d --dev      dvd device to read from (default is ${bb}/dev/dvd${r})
  -q --dir      dvd directory to read from
  -i --iso      dvd iso image to read from
  -v            be verbose (print id numbers)
     --version  show ${suite_name} version"

shorts="d:q:i:v"
longs="dev:,dir:,iso:,version"
eval $(get_parsecmd "$tool_name" "$shorts" "$longs")

while true; do
    case "$1" in
        -d|--dev     ) dvd_device="$2"; shift 2;;
        -q|--dir     ) dvd_device="$2";dvdisdir="-q "; shift 2;;
        -i|--iso     ) dvd_device="$2";dvdisdir="-q "; shift 2;;
        -v           ) verbose="y"; shift;;
           --version ) print_version;;
        --           ) shift ; break ;;
    esac
done

display_tool_banner


if [[ "$dvd_device" ]]; then
    dvd_device="\"$(escape_chars "$dvd_device")\""
fi

echo -e " * Scanning DVD for titles..."


cmd="$lsdvd -avs $dvdisdir $dvd_device 2>&1"
lsdvd_output=$(bash -c "$cmd")

if [[ $? != 0 ]]; then
    echo -en "${e}" ; echo "$lsdvd_output"; echo -en ${r}
    echo -e "$usage"
    exit 2
fi


titlenos=$(echo "$lsdvd_output" | $egrep "^Title" | $awk '{ print $2 }' | $tr -d ',')

for titleno in $titlenos; do
    title=$(echo "$lsdvd_output" | $sed -n "/^Title: $titleno/, /^$/p")
    length=$(echo "$title" | $egrep "^Title: $titleno" | $awk '{ print $4 }' | $sed 's|\(.*\)\..*|\1|g')
    aids=($(echo "$title" | $egrep "Audio:" | $awk '{ print $21 }' | $xargs))
    alangs=($(echo "$title" | $egrep "Audio:" | $awk '{ print $4 }' | $xargs))
    sids=($(echo "$title" | $egrep "Subtitle:" | $awk '{ print $11 }' | $tr -d ',' | $xargs))
    slangs=($(echo "$title" | $egrep "Subtitle:" | $awk '{ print $4 }' | $xargs))

    echo -en   "${b}${titleno}"
    echo -en "  ${r}length: ${bb}${length}"

    if [[ "$alangs" ]]; then
        echo -en "  ${r}audio: "
        i=0
        for alang in ${alangs[*]}; do
            echo -en "${bb}${alang}${r} "
            if [[ "$verbose" ]]; then
                aid=$(( ${aids[$i]} )) # convert from hex
                echo -en "${it}${aid}${r} "
                i=$(( $i+1 ))
            fi
        done
    fi

    if [[ "$slangs" ]]; then
        echo -en " ${r}subs: "
        i=0
        for slang in ${slangs[*]}; do
            echo -en "${bb}${slang}${r} "
            if [[ "$verbose" ]]; then
                sid=$(( ${sids[$i]} )) # convert from hex
                echo -en "${it}${sid}${r} "
                i=$(( $i+1 ))
            fi
        done
    fi

    echo -e ${r}
done

echo -e "${r}\nTo watch a title:"
echo -e " ${b}mplayer       dvd://${bb}01${b}     -alang ${bb}en${b}  -slang ${bb}en/off${r}"

echo -e "${r}To rip titles:"
echo -e " ${b}undvd         -t ${bb}01,02,03${b}  -a ${bb}en${b}      -s ${bb}en/off${r}"
