#!/bin/bash
#
# Author: Martin Matusiak <numerodix@gmail.com>
# Licensed under the GNU Public License, version 3.


# load constants and functions
p=$(dirname $(readlink -f $0)); . $p/lib.sh

display_tool_banner

usage="Usage:  ${b}${tool_name} ${r}[${bb}<file(s)>${r} | ${b}--dev ${bb}/dev/dvd${r} | ${b}--dir ${bb}/path${r} | ${b}--iso ${bb}disc.iso${r}]
  <file(s)> files to read
  -d --dev      dvd device to read from (default is ${bb}/dev/dvd${r})
  -q --dir      dvd directory to read from
  -i --iso      dvd iso image to read from"

shorts="d:q:i:"
longs="dev:,dir:,iso:"
eval $(get_parsecmd "$tool_name" "$shorts" "$longs")

while true; do
	case "$1" in
		-d|--dev ) input_dvd_device="$2"; shift 2;;
		-q|--dir ) input_dvd_device="$2"; shift 2;;
		-i|--iso ) input_dvd_device="$2"; shift 2;;
		--) shift ; break ;;
		* ) break ;;
	esac
done

if [[ ! "$input_dvd_device" && ! "$@" ]]; then
	echo -e "$usage"
	exit 1
fi


# Build array either of dvd titles or files given as input

files=() ; i=0
if [[ "$input_dvd_device" ]]; then
	cmd="mplayer -ao null -vo null -frames 0 -identify -dvd-device \"$input_dvd_device\" dvd:// 2>&1"
	mplayer_output=$($bash -c "$cmd")
	titles=$( echo "$mplayer_output" | $grep "ID_DVD_TITLES" | $sed "s|ID_DVD_TITLES=\(.*\)|\1|g" )
	if [[ "$titles" ]]; then
		for f in $($seq 1 $titles); do
			files[$i]="$f"
			i=$(( $i+1 ))
		done
	else
		echo -e "${e}Could not read from $input_dvd_device${r}"
		exit 1
	fi
else
	for f in "$@"; do
		files[$i]="$f"
		i=$(( $i+1 ))
	done
fi


display_title_line "header"
for file in "${files[@]}"; do
	if [[ ! "$input_dvd_device" && ! -e "$file" ]]; then
		echo -e "${e}File $file does not exist"
		exit 1
	fi

	if [[ "$input_dvd_device" ]]; then
		filename="$file"
		filesize="-1"
		info=($(examine_title "" "$input_dvd_device" "$file"))
	else
		filename=$(basename "$file")

		filesize=$(stat "$file" | $grep "Size:" | $sed "s|.*Size: \([0-9]*\).*|\1|g")
		filesize=$(echo "scale=0; $filesize/1024/1024" | $bc)  # convert to mb

		info=($(examine_title "$file"))
	fi
	
	width=${info[0]}

	height=${info[1]}
	
	fps=${info[2]}
	
	length=${info[3]}
	
	bitrate=$( echo "scale=0; ${info[4]}/1024" | $bc )  # convert to kbps
	if [[ "$bitrate" ]]; then
		bpp=$(compute_bpp "$width" "$height" "$fps" "$length" "" "$bitrate")
	fi

	format=${info[5]}

	passes="0"

	display_title "$width" "$height" "$fps" "$length" "$bpp" "$bitrate" "$passes" "$format" "$filesize" "$filename"
done
